name: Google News (Keyword) RSS to Discord

on:
  schedule:
    - cron: '*/30 * * * *'  # 30분마다 실행
  workflow_dispatch:

env:
  DISCORD_WEBHOOK_KEYWORD: ${{ secrets.DISCORD_WEBHOOK_GOOGLENEWS_KEYWORD }}
  DISCORD_AVATAR_KEYWORD: ${{ secrets.DISCORD_AVATAR_GOOGLENEWS_KEYWORD }}
  DISCORD_USERNAME_KEYWORD: ${{ secrets.DISCORD_USERNAME_GOOGLENEWS_KEYWORD }}
  INITIALIZE_MODE_KEYWORD: ${{ secrets.INITIALIZE_MODE_GOOGLENEWS_KEYWORD }}
  ADVANCED_FILTER_KEYWORD: ${{ secrets.ADVANCED_FILTER_GOOGLENEWS_KEYWORD }}
  DATE_FILTER_KEYWORD: ${{ secrets.DATE_FILTER_GOOGLENEWS_KEYWORD }}
  ORIGIN_LINK_KEYWORD: ${{ secrets.ORIGIN_LINK_GOOGLENEWS_KEYWORD }}
  KEYWORD_MODE: ${{ secrets.KEYWORD_MODE }}
  KEYWORD: ${{ secrets.KEYWORD }}
  RSS_URL: ${{ secrets.RSS_URL_GOOGLENEWS_KEYWORD }}
  AFTER_DATE: ${{ secrets.AFTER_DATE }}
  BEFORE_DATE: ${{ secrets.BEFORE_DATE }}
  WHEN: ${{ secrets.WHEN }}
  HL: ${{ secrets.HL }}
  GL: ${{ secrets.GL }}
  CEID: ${{ secrets.CEID }}

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install requests python-dateutil beautifulsoup4

      - name: Get workflow ID
        id: get_workflow_id
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const workflow = workflows.data.workflows.find(wf => wf.path.endsWith('googlenews-keyword_to_discord.yml'));
            if (!workflow) throw new Error('Workflow not found');
            return workflow.id.toString();

      - name: Get latest successful run ID
        id: get_latest_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const workflowId = "${{ steps.get_workflow_id.outputs.result }}";
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              status: 'success'
            });
            return workflowRuns.data.workflow_runs[0]?.id.toString() || '';

      - name: Download previous database
        if: env.INITIALIZE_MODE_KEYWORD != 'true' && steps.get_latest_run.outputs.result != ''
        uses: actions/download-artifact@v4
        with:
          name: googlenews_keyword_database
          run-id: ${{ steps.get_latest_run.outputs.result }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if database exists or initialize
        id: check_db
        run: |
          if [ "${{ secrets.INITIALIZE_MODE_GOOGLENEWS_KEYWORD }}" == "true" ] || [ ! -f google_news_keyword.db ] || [ ! -s google_news_keyword.db ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Initializing or creating new database"
            rm -f google_news_keyword.db
            touch google_news_keyword.db
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Read Google News RSS and Post to Discord
        env:
          DISCORD_WEBHOOK_KEYWORD: ${{ secrets.DISCORD_WEBHOOK_GOOGLENEWS_KEYWORD }}
          DISCORD_AVATAR_KEYWORD: ${{ secrets.DISCORD_AVATAR_GOOGLENEWS_KEYWORD }}
          DISCORD_USERNAME_KEYWORD: ${{ secrets.DISCORD_USERNAME_GOOGLENEWS_KEYWORD }}
          INITIALIZE_MODE_KEYWORD: ${{ secrets.INITIALIZE_MODE_GOOGLENEWS_KEYWORD }}
          ADVANCED_FILTER_KEYWORD: ${{ secrets.ADVANCED_FILTER_GOOGLENEWS_KEYWORD }}
          DATE_FILTER_KEYWORD: ${{ secrets.DATE_FILTER_GOOGLENEWS_KEYWORD }}
          ORIGIN_LINK_KEYWORD: ${{ secrets.ORIGIN_LINK_GOOGLENEWS_KEYWORD }}
          KEYWORD_MODE: ${{ secrets.KEYWORD_MODE }}
          KEYWORD: ${{ secrets.KEYWORD }}
          RSS_URL: ${{ secrets.RSS_URL }}
          AFTER_DATE: ${{ secrets.AFTER_DATE }}
          BEFORE_DATE: ${{ secrets.BEFORE_DATE }}
          WHEN: ${{ secrets.WHEN }}
          HL: ${{ secrets.HL }}
          GL: ${{ secrets.GL }}
          CEID: ${{ secrets.CEID }}
        run: |
          python .github/scripts/googlenews-keyword_to_discord.py

      - name: Upload updated database
        uses: actions/upload-artifact@v4
        with:
          name: googlenews_keyword_database
          path: google_news_keyword.db
          retention-days: 90

      - name: Debug Information
        if: always()
        run: |
          echo "Latest successful run ID: ${{ steps.get_latest_run.outputs.result }}"
          echo "INITIALIZE_MODE_KEYWORD: ${{ secrets.INITIALIZE_MODE_GOOGLENEWS_KEYWORD }}"
          echo "Workspace contents:"
          ls -la
          echo "Database file size:"
          ls -lh google_news_keyword.db || echo "Database file not found"
          echo "Database contents (if exists):"
          sqlite3 google_news_keyword.db "SELECT COUNT(*) FROM news_items;" || echo "Unable to query database"
