name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 1 * *"  # 매월 1일 00:00 UTC에 실행
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          gh_token: ${{ secrets.GH_PAT }}