name: Keepalive Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # 권한 설정
  
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: "0"
          gh_token: ${{ secrets.GH_PAT }}  # GitHub 토큰
          use_api: false  # 더미 커밋 사용 설정